# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-04 18:14
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sysusers', '0002_auto_20161004_1732'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.TextField(blank=True, max_length=500)),
                ('location', models.CharField(blank=True, max_length=30)),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='custumer',
            name='user',
        ),
        migrations.RemoveField(
            model_name='usercontact',
            name='user',
        ),
        migrations.DeleteModel(
            name='Custumer',
        ),
        migrations.DeleteModel(
            name='UserContact',
        ),
    ]
