# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-05 14:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sysusers', '0006_auto_20161005_1432'),
    ]

    operations = [
        migrations.RenameField(
            model_name='custumer',
            old_name='country',
            new_name='country_id',
        ),
        migrations.RenameField(
            model_name='custumercontact',
            old_name='country',
            new_name='country_id',
        ),
        migrations.RenameField(
            model_name='custumercontact',
            old_name='custumer',
            new_name='custumer_id',
        ),
    ]
