# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-16 08:00
from __future__ import unicode_literals

from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sysusers', '0007_auto_20161005_1459'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='custumer',
            options={'verbose_name': 'user', 'verbose_name_plural': 'users'},
        ),
        migrations.AlterModelManagers(
            name='custumer',
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.RemoveField(
            model_name='custumer',
            name='email',
        ),
        migrations.RemoveField(
            model_name='custumer',
            name='firstname',
        ),
        migrations.RemoveField(
            model_name='custumer',
            name='id',
        ),
        migrations.RemoveField(
            model_name='custumer',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='custumer',
            name='is_contact',
        ),
        migrations.RemoveField(
            model_name='custumer',
            name='is_custumer',
        ),
        migrations.RemoveField(
            model_name='custumer',
            name='is_superuser',
        ),
        migrations.RemoveField(
            model_name='custumer',
            name='name',
        ),
        migrations.RemoveField(
            model_name='custumer',
            name='pref_contry',
        ),
        migrations.RemoveField(
            model_name='custumer',
            name='username',
        ),
        migrations.AddField(
            model_name='custumer',
            name='user_ptr',
            field=models.OneToOneField(auto_created=True, default=1, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
