# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-16 19:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sysusers', '0008_auto_20161016_0800'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='custumercontact',
            name='is_superuser',
        ),
        migrations.AlterField(
            model_name='custumercontact',
            name='country_id',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='credata.Country'),
        ),
    ]
