# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-16 19:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sysusers', '0009_auto_20161016_1928'),
    ]

    operations = [
        migrations.AddField(
            model_name='custumer',
            name='is_custumer',
            field=models.BooleanField(default=True, verbose_name='Client'),
        ),
    ]
