# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-26 21:05
from __future__ import unicode_literals

import django.contrib.auth.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0008_alter_user_username_max_length'),
        ('sysusers', '0010_custumer_is_custumer'),
    ]

    operations = [
        migrations.CreateModel(
            name='Testuser',
            fields=[
            ],
            options={
                'ordering': ['username'],
                'proxy': True,
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
