# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-26 21:08
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sysusers', '0011_testuser'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='testuser',
            options={'ordering': ['last_name']},
        ),
    ]
