# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-27 17:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Nom Categorie')),
                ('code', models.CharField(max_length=10, unique=True, verbose_name='Code Categorie')),
                ('slug', models.SlugField(blank=True, help_text='Unique value for product page URL, created from name.', unique=True, verbose_name='slug')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('is_active', models.BooleanField(default=True, verbose_name='Actif')),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('update_date', models.DateTimeField(auto_now=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='credata.Category')),
            ],
            options={
                'ordering': ['-name', '-is_active'],
            },
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Nom pays')),
                ('code', models.CharField(max_length=4, unique=True, verbose_name='Code pays')),
                ('indicatif', models.CharField(blank=True, max_length=4, unique=True, verbose_name='Indicatif pays')),
                ('width', models.IntegerField(default=64, verbose_name='Largeur')),
                ('height', models.IntegerField(default=43, verbose_name='Hauteur')),
                ('flag', models.ImageField(blank=True, height_field='height', null=True, upload_to=b'', verbose_name='Drapeau', width_field='width')),
                ('is_active', models.BooleanField(default=True, verbose_name='Actif')),
                ('create_date', models.DateTimeField(auto_now_add=True, verbose_name='Date de creation')),
                ('update_date', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
            ],
            options={
                'ordering': ['-name'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nom produit')),
                ('code', models.CharField(max_length=10, verbose_name='R\xe9f\xe9rence')),
                ('icon', models.ImageField(upload_to=b'')),
                ('price', models.DecimalField(decimal_places=0, default=0, max_digits=6, verbose_name='Prix de vente')),
                ('is_active', models.BooleanField(default=True, verbose_name='Actif')),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('update_date', models.DateTimeField(auto_now=True)),
                ('category_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='credata.Category')),
            ],
            options={
                'ordering': ['-name', '-code', 'category_id'],
            },
        ),
    ]
