# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-27 17:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('credata', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CodeUssd',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Non du code ussd EX: Transfert credit.', max_length=50, verbose_name='Nom USSD')),
                ('code', models.CharField(help_text='Ex: *124#.', max_length=8, unique=True, verbose_name='Code')),
                ('ussd_type', models.CharField(choices=[('nome', 'NONE'), ('credit', 'Tranfert de Cr\xe9dit'), ('money', "Tranfert de d'argent"), ('data', 'Tranfert de data')], default='none', max_length=2, verbose_name='Type Ussd')),
                ('is_active', models.BooleanField(default=True, verbose_name='Actif')),
                ('create_date', models.DateTimeField(auto_now_add=True, verbose_name='Date de creation')),
                ('update_date', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
            ],
            options={
                'ordering': ['-name'],
            },
        ),
        migrations.CreateModel(
            name='Operator',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Nom op\xe9rateur')),
                ('code', models.CharField(max_length=8, unique=True, verbose_name='Code op\xe9rateur')),
                ('logo', models.ImageField(blank=True, height_field='height', null=True, upload_to=b'', verbose_name='Logo opr\xe9rateur', width_field='width')),
                ('is_active', models.BooleanField(default=True, verbose_name='Actif')),
                ('create_date', models.DateTimeField(auto_now_add=True, verbose_name='Date de creation')),
                ('update_date', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
                ('country_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='credata.Country')),
            ],
            options={
                'ordering': ['-name'],
            },
        ),
        migrations.AddField(
            model_name='codeussd',
            name='operator_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='credata.Operator'),
        ),
    ]
