# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-27 17:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credata', '0002_auto_20160927_1717'),
    ]

    operations = [
        migrations.AlterField(
            model_name='codeussd',
            name='ussd_type',
            field=models.CharField(choices=[('nome', 'NONE'), ('credit', 'Tranfert de Cr\xe9dit'), ('money', "Tranfert de d'argent"), ('data', 'Tranfert de data')], default='none', max_length=30, verbose_name='Type Ussd'),
        ),
    ]
