# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-27 19:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credata', '0004_operatorprefixe'),
    ]

    operations = [
        migrations.AlterField(
            model_name='operatorprefixe',
            name='prefixe',
            field=models.CharField(help_text='EX 96 ou 92 ou 90.', max_length=2, verbose_name='Prefixe operateur'),
        ),
    ]
