# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-27 20:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credata', '0005_auto_20160927_1952'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.CharField(max_length=10, verbose_name='id order')),
                ('operator_id', models.CharField(max_length=10, verbose_name='code ussd')),
                ('country_id', models.CharField(max_length=10, verbose_name='Country code')),
                ('state', models.CharField(choices=[('pending', 'En attente'), ('processing', 'En traitement'), ('completed', 'Complete'), ('failed', 'Echouer')], default='none', max_length=30, verbose_name='Type Ussd')),
                ('create_date', models.DateTimeField(auto_now_add=True, verbose_name='Date de creation')),
                ('update_date', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
            ],
            options={
                'ordering': ['-order_id', 'country_id'],
            },
        ),
    ]
