# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-01 07:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credata', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='operator',
            name='codeussds',
            field=models.ManyToManyField(blank=True, to='credata.CodeUssd'),
        ),
        migrations.AlterField(
            model_name='operator',
            name='prefixes',
            field=models.ManyToManyField(blank=True, to='credata.OperatorPrefixe'),
        ),
    ]
