# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-01 07:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('credata', '0002_auto_20161001_0731'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='operatorprefixe',
            name='country_id',
        ),
    ]
