# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-01 12:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('credata', '0003_remove_operatorprefixe_country_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Franc CFA.', max_length=24, verbose_name='Nom devise')),
                ('code', models.CharField(help_text='FCFA, \xa3, $ ou \u20ac...', max_length=8, verbose_name='Symbole')),
                ('is_active', models.BooleanField(default=True, verbose_name='Actif')),
                ('create_date', models.DateTimeField(auto_now_add=True, verbose_name='Date de creation')),
                ('update_date', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
                ('countrys', models.ManyToManyField(blank=True, to='credata.Country')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sex', models.CharField(choices=[('nome', 'NONE'), ('M', 'Masculin'), ('F', 'Feminin')], default='none', max_length=1, verbose_name='Sexe')),
                ('name', models.CharField(help_text='Saisir le nom de famille', max_length=64, verbose_name='Nom de famille')),
                ('firstname', models.CharField(help_text='Entrez les pr\xe9noms', max_length=64, verbose_name='Pr\xe9noms')),
                ('username', models.CharField(max_length=24, verbose_name='Compte de connexion')),
                ('is_active', models.BooleanField(default=True, verbose_name='Actif')),
                ('pref_contry', models.CharField(blank=True, help_text='Prefixe pays', max_length=4, verbose_name='Prefixe Pays')),
                ('tel', models.CharField(help_text='Votre num\xe9ro de t\xe9l\xe9phone', max_length=12, verbose_name='T\xe9l\xe9phone')),
                ('address', models.CharField(blank=True, help_text='Rue 31 Avenue Steimeiz', max_length=256, verbose_name='Adresse')),
                ('email', models.EmailField(blank=True, max_length=50)),
                ('is_user', models.BooleanField(default=True, verbose_name='Utilisateur simple')),
                ('is_contact', models.BooleanField(default=False, verbose_name='Utilisateur simple')),
                ('country_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='credata.Country')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='UserContact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sex', models.CharField(choices=[('nome', 'NONE'), ('M', 'Masculin'), ('F', 'Feminin')], default='none', max_length=1, verbose_name='Sexe')),
                ('name', models.CharField(help_text='Saisir le nom de famille', max_length=64, verbose_name='Nom de famille')),
                ('firstname', models.CharField(help_text='Entrez les pr\xe9noms', max_length=64, verbose_name='Pr\xe9noms')),
                ('username', models.CharField(max_length=24, verbose_name='Compte de connexion')),
                ('is_active', models.BooleanField(default=True, verbose_name='Actif')),
                ('pref_contry', models.CharField(blank=True, help_text='Prefixe pays', max_length=4, verbose_name='Prefixe Pays')),
                ('tel', models.CharField(help_text='Votre num\xe9ro de t\xe9l\xe9phone', max_length=12, verbose_name='T\xe9l\xe9phone')),
                ('address', models.CharField(blank=True, help_text='Rue 31 Avenue Steimeiz', max_length=256, verbose_name='Adresse')),
                ('email', models.EmailField(blank=True, max_length=50)),
                ('is_contact', models.BooleanField(default=True, verbose_name='Utilisateur simple')),
                ('is_user', models.BooleanField(default=False, verbose_name='Utilisateur simple')),
                ('country_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='credata.Country')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='country',
            name='currencys',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='credata.Currency'),
            preserve_default=False,
        ),
    ]
