# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-01 13:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('credata', '0006_country_currencys'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='currency',
            name='countrys',
        ),
        migrations.RemoveField(
            model_name='country',
            name='currencys',
        ),
        migrations.DeleteModel(
            name='Currency',
        ),
    ]
