# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-01 16:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('credata', '0008_auto_20161001_1349'),
    ]

    operations = [
        migrations.AlterField(
            model_name='country',
            name='currencys',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='credata.Currency'),
        ),
    ]
