# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-04 07:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credata', '0010_auto_20161001_2017'),
    ]

    operations = [
        migrations.AlterField(
            model_name='country',
            name='flag',
            field=models.ImageField(blank=True, height_field='height', null=True, upload_to='media/flags/', verbose_name='Drapeau', width_field='width'),
        ),
    ]
