# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-05 15:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credata', '0011_auto_20161004_0715'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='country_id',
        ),
        migrations.RemoveField(
            model_name='usercontact',
            name='country_id',
        ),
        migrations.AddField(
            model_name='currency',
            name='symbole',
            field=models.CharField(default=1, help_text='FCFA, \xa3, $ ou \u20ac...', max_length=8, verbose_name='Symbole'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='currency',
            name='code',
            field=models.CharField(help_text='xof, ...', max_length=24, verbose_name='Nom devise'),
        ),
        migrations.AlterField(
            model_name='operator',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='media/operators/', verbose_name='Logo opr\xe9rateur'),
        ),
        migrations.AlterField(
            model_name='product',
            name='icon',
            field=models.ImageField(blank=True, upload_to='media/products/'),
        ),
        migrations.DeleteModel(
            name='User',
        ),
        migrations.DeleteModel(
            name='UserContact',
        ),
    ]
