# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-16 19:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credata', '0012_auto_20161005_1503'),
    ]

    operations = [
        migrations.AddField(
            model_name='country',
            name='is_couvrage',
            field=models.BooleanField(default=False, verbose_name='Actif'),
        ),
        migrations.AlterField(
            model_name='country',
            name='flag',
            field=models.ImageField(blank=True, height_field='height', null=True, upload_to='static/flags/', verbose_name='Drapeau', width_field='width'),
        ),
        migrations.AlterField(
            model_name='operator',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='static/operators/', verbose_name='Logo opr\xe9rateur'),
        ),
        migrations.AlterField(
            model_name='product',
            name='icon',
            field=models.ImageField(blank=True, upload_to='static/products/'),
        ),
        migrations.AlterField(
            model_name='task',
            name='state',
            field=models.CharField(choices=[('0', 'En traitement'), ('1', 'Complete'), ('2', 'Echouer')], default='0', max_length=30, verbose_name='Type Ussd'),
        ),
    ]
