# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-27 22:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credata', '0015_custumer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='custumer',
            name='date_of_birth',
            field=models.DateField(blank=True),
        ),
    ]
