# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-28 09:26
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0008_alter_user_username_max_length'),
        ('credata', '0016_auto_20161027_2223'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profil',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('birthday', models.DateField(blank=True, null=True, verbose_name='date de naissance')),
                ('sexe', models.CharField(choices=[('H', 'Homme'), ('F', 'Femme'), ('A', 'Autre')], default='H', max_length=1)),
                ('image', models.ImageField(blank=True, default='profil/defaultProfil.png', null=True, upload_to='profil/%Y/%m/%d')),
                ('apropos', models.TextField(blank=True, max_length=1000, null=True)),
            ],
        ),
    ]
