# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-28 16:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('credata', '0017_profil'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profil',
            name='apropos',
        ),
        migrations.RemoveField(
            model_name='profil',
            name='birthday',
        ),
        migrations.AddField(
            model_name='profil',
            name='address',
            field=models.TextField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='profil',
            name='country_id',
            field=models.ForeignKey(blank=True, default=5, on_delete=django.db.models.deletion.CASCADE, to='credata.Country'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profil',
            name='create_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Date de creation'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profil',
            name='is_custumer',
            field=models.BooleanField(default=False, help_text='Cochez pour un client', verbose_name='Client'),
        ),
        migrations.AddField(
            model_name='profil',
            name='tel',
            field=models.CharField(default=90909090, help_text='Votre num\xe9ro de t\xe9l\xe9phone sans pr\xe9fixe pays', max_length=12, verbose_name='T\xe9l\xe9phone'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profil',
            name='update_date',
            field=models.DateTimeField(auto_now=True, verbose_name='Date de modification'),
        ),
        migrations.AlterField(
            model_name='product',
            name='icon',
            field=models.ImageField(blank=True, upload_to='static/products'),
        ),
        migrations.AlterField(
            model_name='profil',
            name='image',
            field=models.ImageField(blank=True, default='profil/defaultProfil.png', null=True, upload_to='static/profil/%Y/%m/%d'),
        ),
    ]
