# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-29 03:51
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0008_alter_user_username_max_length'),
        ('credata', '0018_auto_20161028_1637'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactUser',
            fields=[
                ('name', models.CharField(max_length=64, verbose_name='Nom de famille')),
                ('firstname', models.CharField(max_length=64, verbose_name='Pr\xe9noms')),
                ('sexe', models.CharField(choices=[('H', 'Homme'), ('F', 'Femme'), ('A', 'Autre')], default='H', max_length=1)),
                ('profil', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('tel', models.CharField(help_text='Votre num\xe9ro de t\xe9l\xe9phone sans pr\xe9fixe pays', max_length=12, verbose_name='T\xe9l\xe9phone')),
                ('is_custumer', models.BooleanField(default=False, help_text='Cochez pour un client', verbose_name='Client')),
                ('image', models.ImageField(blank=True, default='profil/defaultProfil.png', null=True, upload_to='static/profil/%Y/%m/%d')),
                ('address', models.TextField(blank=True, max_length=256, null=True)),
                ('create_date', models.DateTimeField(auto_now_add=True, verbose_name='Date de creation')),
                ('update_date', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
                ('country_id', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='credata.Country')),
            ],
        ),
        migrations.RemoveField(
            model_name='custumer',
            name='country_id',
        ),
        migrations.DeleteModel(
            name='Custumer',
        ),
    ]
