# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-29 04:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credata', '0021_contactuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactuser',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Cochez pour activer ou d\xe9sactiver', verbose_name='Actif'),
        ),
    ]
